-- Set your context
USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;

-- CRITICAL: Set cost-saving auto-suspend
ALTER WAREHOUSE COMPUTE_WH SET AUTO_SUSPEND = 60;

-- Create your personal database
CREATE DATABASE IF NOT EXISTS Justin_DEV_DB
    COMMENT = 'Personal development database';

-- Create schemas for the Medallion architecture
CREATE SCHEMA IF NOT EXISTS Justin_DEV_DB.BRONZE;
CREATE SCHEMA IF NOT EXISTS Justin_DEV_DB.SILVER;
CREATE SCHEMA IF NOT EXISTS Justin_DEV_DB.GOLD;

-- Verify creation
SHOW SCHEMAS IN DATABASE Justin_DEV_DB;


USE DATABASE SNOWFLAKE_SAMPLE_DATA;
USE SCHEMA TPCH_SF1;


-- List all tables
SHOW TABLES;

-- Count rows in a large table
SELECT COUNT(*) FROM ORDERS;

-- Basic aggregation
SELECT 
    O_ORDERSTATUS,
    COUNT(*) AS order_count
FROM ORDERS
GROUP BY O_ORDERSTATUS;

SELECT * FROM ORDERS LIMIT 10;


SELECT O_ORDERPRIORITY, AVG(O_TOTALPRICE) AS avg_price 
FROM ORDERS
GROUP BY O_ORDERPRIORITY
ORDER BY avg_price DESC;

SELECT O_ORDERSTATUS, COUNT(*)
FROM ORDERS
GROUP BY O_ORDERSTATUS;

