SELECT 
    CURRENT_WAREHOUSE() AS warehouse,
    CURRENT_DATABASE() AS database,
    CURRENT_SCHEMA() AS schema,
    CURRENT_ROLE() AS role;


USE DATABASE SNOWFLAKE_SAMPLE_DATA;
USE SCHEMA TPCH_SF1;

-- Customer distribution by market segment
SELECT 
    C_MKTSEGMENT,
    COUNT(*) AS customer_count,
    ROUND(AVG(C_ACCTBAL), 2) AS avg_balance
FROM CUSTOMER
GROUP BY C_MKTSEGMENT
ORDER BY customer_count DESC;


-- Top 10 customers by order volume
SELECT 
    c.C_NAME AS customer_name,
    n.N_NAME AS nation,
    COUNT(o.O_ORDERKEY) AS order_count,
    SUM(o.O_TOTALPRICE) AS total_spent
FROM CUSTOMER c
JOIN ORDERS o ON c.C_CUSTKEY = o.O_CUSTKEY
JOIN NATION n ON c.C_NATIONKEY = n.N_NATIONKEY
GROUP BY c.C_NAME, n.N_NAME
ORDER BY total_spent DESC
LIMIT 10;


SELECT
	EXTRACT(YEAR FROM O_ORDERDATE) AS YEAR_OF_ORDER,
	AVG(O_TOTALPRICE)
FROM ORDERS
GROUP BY YEAR_OF_ORDER


SELECT 
    QUERY_TEXT,
    EXECUTION_STATUS,
    TOTAL_ELAPSED_TIME/1000 AS seconds,
    BYTES_SCANNED/1000000 AS mb_scanned,
    ROWS_PRODUCED
FROM TABLE(INFORMATION_SCHEMA.QUERY_HISTORY())
WHERE QUERY_TYPE = 'SELECT'
ORDER BY START_TIME DESC
LIMIT 10;